class Lists{
  // List<String> MealNames = ['Dal Fry','Chicken Handi','Tandoori Chicken','Lamb Biryani','Baingan Bharta','Lamb Rogan Josh',
  //   'Recheado Masala Fish','Nutty Chicken Curry','Matar Paneer','Kidney Bean Curry','Smoked Haddok Kedgeree',''
  // ];
  List <String> MealNames = ['Apple Frangipan Tart','Apple & Blackberry Crumble', 'Apam balik','Ayam Percik','Bakewell tart',
    'Bread and Butter Pudding','Beef Wellington','Baingan Bharta','Beef Brisket Pot Roast','Beef Sunday Roast','Braised Beef Chilli',
    'Brocolli & Stilton soup','Bean & Sausage Hotpot','Banana Pancakes','Battenberg Cake','Brie wrapped in prosciutto & brioche',
    'Boulangère Potatoes','BeaverTails','Brown Stew Chicken','Baked salmon with fennel & tomatoes','Budino Di Ricotta',
    'Breakfast Potatoes','Bitterballen (Dutch meatballs)','Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber',
    'Big Mac','Bigos (Hunters Stew)','Boxty Breakfast','Chocolate Gateau','Chicken Enchilada Casserole','Cream Cheese Tart',
    'Christmas Pudding Flapjack','Chicken Handi','Chicken Alfredo Primavera','Chicken Fajita Mac and Cheese','Cajun spiced fish tacos',
    'Crock Pot Chicken Baked Tacos','Chicken Karaage','Chilli prawn linguine','Creamy Tomato Soup','Chicken & mushroom Hotpot','Chicken Couscous',
    'Chocolate Avocado Mousse','Choc Chip Pecan Pie','Chocolate Raspberry Brownies','Chickpea Fajitas','Chicken Ham and Leek Pie','Chicken Parmentier',
    'Carrot Cake','Chelsea Buns','Chocolate Souffle','Chinon Apple Tarts','Chicken Marengo','Canadian Butter Tarts','Chicken Basquaise',
    'Callaloo Jamaican Style','Chicken Congee','Chocolate Caramel Crispy','Chakchouka','Cashew Ghoriba Biscuits','Corba','Christmas Pudding Trifle',
    'Classic Christmas pudding','Christmas cake','Crispy Sausages and Greens','Chicken Quinoa Greek Salad','Chick-Fil-A Sandwich','Dal fry',
    'Dundee cake','Eton Mess','Eccles Cakes','English Breakfast','Escovitch Fish','Egg Drop Soup','Egyptian Fatteh','Fish pie','French Lentils With Garlic and Thyme',
    'Fettucine alfredo','Full English Breakfast','French Onion Soup','Flamiche','French Omelette','Fish Stew with Rouille','Fennel Dauphinoise',
    'Fruit and Cream Cheese Breakfast Pastries','French Onion Chicken with Roasted Carrots & Mashed Potatoes','Ful Medames','Feteer Meshaltet',
    'Fish fofos','Garides Saganaki','Grilled Mac and Cheese Sandwich',"General Tso's Chicken",'Gigantes Plaki','Gołąbki (cabbage roll)',
    'Hot Chocolate Fudge','Hot and Sour Soup','Home-made Mandazi','Honey Yogurt Cheesecake','Irish stew','Jam Roly-Poly','Japanese gohan rice',
    'Japanese Katsudon','Kentucky Fried Chicken','Katsu Chicken curry','Key Lime Pie','Kidney Bean Curry','Kafteji','Krispy Kreme Donut',
    'Koshari','Lasagne','Leblebi Soup','Lamb Tzatziki Burgers', 'Mediterranean Pasta Salad','Massaman Beef curry', 'Mushroom & Chestnut Rotolo',
   ' Matar Paneer',' Minced Beef Pie', 'McSinghs Scotch pie', 'Madeira Cake', 'Montreal Smoked Meat', 'Ma Po Tofu', 'Mbuzi Choma (Roasted Goat)',
    'Mince Pies', 'Moussaka', 'Mulukhiyah',' Mustard champ',' Moroccan Carrot Soup',' Mee goreng mamak','Nutty Chicken Curry', 'New York cheesecake',
    ' Nanaimo Bars', 'Nasi lemak','Osso Buco alla Milanese',' Oxtail with broad beans','Pad See Ew', 'Potato Gratin with Chicken', 'Poutine',
    'Pilchard puttanesca', 'Pork Cassoulet',' Pancakes', 'Pumpkin Pie', 'Peanut Butter Cheesecake', 'Peach & Blueberry Grunt',
   ' Parkin Cake', 'Pear Tarte Tatin',' Provençal Omelette Cake', 'Prawn & Fennel Bisque', 'Pate Chinois',' Pouding chomeur',
    'Peanut Butter Cookies', 'Pizza Express Margherita',' Paszteciki (Polish Pasties)',' Pierogi (Polish Dumplings)', 'Polskie Naleśniki (Polish Pancakes)',
  '  Piri-piri chicken and slaw',' Portuguese prego with green piri-piri', 'Portuguese barbecued pork (Febras assadas)',' Portuguese fish stew (Caldeirada de peixe)',
    'Portuguese custard tarts','Rigatoni with fennel sausage sauce', 'Rocky Road Fudge',' Recheado Masala Fish', 'Ribollita',' Roasted Eggplant With Tahini',
   ' Pine Nuts', 'and Lentils', 'Rock Cakes',' Ratatouille',' Rappie Pie',' Red Peas Soup',' Roast fennel and aubergine paella',
   ' Rosół (Polish Chicken Soup)', 'Rogaliki (Polish Croissant Cookies)',' Roti john','Spaghetti Bolognese', 'Spicy Arrabiata Penne', 'Smoky Lentil Chili with Squash',
   ' Sticky Toffee Pudding Ultimate', 'Spicy North African Potato Salad', 'Stovetop Eggplant With Harissa',' Chickpeas',' and Cumin Yogurt', 'Salmon Prawn Risotto',
    ' Salted Caramel Cheescake'', Seafood fideuà', 'Spinach & Ricotta Cannelloni', 'Squash linguine', 'Spanish Tortilla', 'Steak and Kidney Pie',
   ' Sticky Toffee Pudding',' Spotted Dick',' Summer Pudding',' Summer Pistou',' Split Pea Soup', 'Sugar Pie', 'Steak Diane',' Saltfish and Ackee',
  '  Sweet and Sour Pork', 'Szechuan Beef',' Shrimp Chow Fun', 'Salmon Avocado Salad', 'Salmon Eggs Eggs Benedict', 'Shakshuka', 'Smoked Haddock Kedgeree',
    'Stamppot', 'Snert (Dutch Split Pea Soup)', 'Spaghetti alla Carbonara', 'Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots',
   ' Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini',' Strawberry Rhubarb Pie',' Stuffed Lamb Tomatoes', 'Sledz w Oleju (Polish Herrings)', 'Shawarma',
   ' Spring onion and prawn empanadas', 'Seri muka kuih','Teriyaki Chicken Casserole', 'Tandoori chicken', 'Thai Green Curry',' Toad In The Hole',
    'Turkey Meatloaf', 'Tuna Nicoise',' Tahini Lentils', 'Three Fish Pie',' Treacle Tart',' Tarte Tatin', 'Three-cheese souffles',
    'Tourtiere', 'Timbits', 'Tunisian Orange Cake', 'Tunisian Lamb Soup',' Tuna and Egg Briks',' Tamiya, Tonkatsu pork','Vegan Lasagna',
    'Vegan Chocolate Cake', 'Vietnamese Grilled Pork (bun-thit-nuong)',' Venetian Duck Ragu',' Vegetarian Casserole',' Vegetarian Chilli',
    'Vegetable Shepherd’s Pie','White chocolate creme brulee',' Wontons','Yaki Udon'];

}